package generics.watercolors;

public enum WaterColors {
		ZINC, LEMON_YELLOW, MEDIUM_YELLOW, DEEP_YELLOW, ORANGE,
		BRILLIANT_RED, CRIMSON, MAGENTA, ROSE_MADDER, VIOLET,
		CERULEAN_BLUE_HUE, PATHALO_BLUE, ULTRAMARINE, COBALT_BLUE_HUE,
		PERMANENT_GREEN, VIRIDIAN_HUE, SAP_GREEN, YELLOW_OCHRE,
		BURNT_SIENNA, RAW_UMBER, BURANT_UMBER, PAYNES_GRAY, IVORY_BLACK
}
